### ISSUE TITLE
Add LDAP authentication

### ISSUE THREAD

**Issue by stuehmer** [hiwitool/hiwitool#4]
LDAP auth should be used a primary means for authentication. If it fails Hiwitool must fall back to local passwords.
This behaviour should help before all users are migrated to LDAP.

**Comment by bkaempgen** [comment]
Good idea. Is dit-j involved, anymore?

**Comment by stuehmer** [comment]
I don't think so, there was a hand-over to @ningyuan of some kind.

**Comment by ningyuan** [comment]
The LDAP auth and the related account management for all hiwi are finished. Further functions of LDAP, for example auth and management for advisers, can be built based on that.
