### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by stuehmer** [hiwitool/hiwitool#5]
After I mark a Hiwi to be *ex-Hiwi* I get this banner: `Der Hiwi wurde erfolgreich activiert.`

It should say something like: `Der Hiwi wurde erfolgreich als Ex-Hiwi markiert.`

**Comment by ningyuan** [comment]
fixed

**Comment by ningyuan** [comment]
fixed #5

**Comment by ningyuan** [comment]
fixed
